version: "3"
services:
  java-postgres:
    image: bitnami/postgresql
    container_name: java-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USERNAME=postgres
    ports:
      - "5431:5432"
    networks:
      - postgres
networks:
  postgres:
    name: postgres
    external: true
